askacademy/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.views.generic import TemplateView, RedirectView

# class RootView(TemplateView):
#     template_name = 'root.html'

urlpatterns = [
    path('', RedirectView.as_view(
        pattern_name='instagram:post_list',
    ), name='root'),
    path('admin/', admin.site.urls),
    path('blog1/', include('blog1.urls')),
    path('instagram/', include('instagram.urls')),
    path('accounts/', include('accounts.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# settings.MEDIA_URL
# settings.MEDIA_ROOT

    import debug_toolbar
    urlpatterns += [
        path('__debug__/',include(debug_toolbar.urls)),
    ]

blog1/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('', views.post_list, name='post_list'),
]

instagram/urls.py
from django.urls import path, register_converter
from . import views
from .converters import YearConverter, MonthConverter, DayConverter


register_converter(YearConverter, 'year')
register_converter(MonthConverter, 'month')
register_converter(DayConverter, 'day')

app_name = 'instagram'
urlpatterns =[
    path('new/', views.post_new, name='post_new'),
    path('', views.post_list, name='post_list'),

    path('<int:pk>/', views.post_detail, name='post_detail'),
    path('<int:pk>/edit/', views.post_edit, name='post_edit'),
    path('<int:pk>/delete/', views.post_delete, name='post_delete'),

    path('archive/', views.post_archive, name='post_archive'),
    path('archive/<year:year>/', views.post_archive_year, name='post_archive_year'),
    # path('archive/<year:year>/<month:month>/', views.post_archive_month, name='post_archive_month'),
    # path('archive/<year:year>/<month:month>/<day:day>/', views.post_archive_day, name='post_archive_day'),
    # path('archives/<year:year>/', views.archives_year)
]

instagram/models.py
from django.db import models
# 권장하지 않음 : User 모델이 변경 될 수 있기 때문
# from django.contrib.auth.models import User

# 권장 : settings의 auth_user_model만 수정하면 되기 때문
# 초반에 설쟁 하는게 중요
from django.conf import settings

# Create your models here.
from django.urls import reverse

# validator 는 직접 구현하면 migration 시 오류가 날 수 있기 때문에
# 기본으로 지원되는 validator 사용 권장
from django.core.validators import MinLengthValidator



class Post(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    message = models.TextField(
        validators=[MinLengthValidator(10)]
    )
    # 삭제 해야 된다면
    # ImageField를 Custom 해서 파일 삭제
    # 배치를 통해서 삭제 하는 방법

    # uplaod_to 는 함수를 지정 할 수 있음 -> 파일 경로를 지정
    photo = models.ImageField(blank=True, upload_to='instagram/post/%Y/%m/%d')
    tag_set = models.ManyToManyField('Tag', blank=True)
    is_public = models.BooleanField(default=False, verbose_name='공개여부')
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)
    def __str__(self):
        #return f"object ({self.id})"
        return self.message

    def get_absolute_url(self):
        return reverse('instagram:post_detail', args=[self.pk])

    class Meta:
        ordering = ['-id']
    # 인자 없는 함수만 가능
    # def message_length(self):
    #     return len(self.message)
    #
    # message_length.short_description = '메세지 글자수'

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE,
                             limit_choices_to={'is_public': True})
    message = models.TextField()
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

class Tag(models.Model):
    name = models.CharField(max_length=50,unique=True)
    # post_set
    def __str__(self):
        return self.name

instagram/forms.py
import re

from django import forms
from .models import Post

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        # fields = '__all__'
        # form 에 지정된 필드에 관해서만 유효성 검사 함
        fields = ['message', 'photo', 'tag_set', 'is_public']

    def clean_message(self):
        message = self.cleaned_data.get('message')
        if message:
            # message에 영어가 잇으면 영어를 없애고 저장하도록 함
            message = re.sub(r'[a-zA-Z]','',message)
        return message

instagram/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import ListView, DetailView, View, ArchiveIndexView, YearArchiveView, CreateView, UpdateView, \
    DeleteView
from django.http import HttpResponse, HttpRequest, Http404
from django.shortcuts import render, get_object_or_404, redirect
from .models import Post
from .forms import PostForm


class PostDeleveView(LoginRequiredMixin, DeleteView):
    model = Post
    success_url = reverse_lazy('instagram:post_list')

post_delete = PostDeleveView.as_view()
#
# def post_delete(request, pk):
#     post = get_object_or_404(Post, pk=pk)
#
#     if request.method == 'POST':
#         post.delete()
#         messages.success(request,'포스팅 삭제했습니다.')
#         return redirect('instagram:post_list')
#     return render(request, 'instagram/post_confirm_delete.html',{
#         'post':post,
#     })

# @login_required -> LoginRequiredMixin
class PostUpdateView(LoginRequiredMixin,UpdateView):
    model = Post
    form_class = PostForm

    def form_valid(self, form):
        messages.success(self.request, '포스팅을 수정 했습니다.')
        return super().form_valid(form)

post_edit = PostUpdateView.as_view()

#
# @login_required
# def post_edit(request, pk):
#     post = get_object_or_404(Post, pk=pk)
#
#     if post.author != request.user:
#         messages.error(request, '작성자만 수정할 수 있습니다.')
#         # post detail 로 이동, get_absolute_url
#         return redirect(post)
#
#     if request.method == 'POST':
#         form = PostForm(request.POST, request.FILES, instance=post)
#         if form.is_valid():
#             post = form.save(commit=False)
#             # request.user 를 사용하려면 필수로  login 되어 있어야 함 -> @login_required 사용
#             post.author = request.user
#             post.save()
#             messages.success(request, '포스팅 수정 완료')
#             # post = form.save(commit=False)
#             # post.save()
#             return redirect(post)
#     else:
#         form = PostForm(instance=post)
#
#     return render(request, 'instagram/post_new.html', {
#         'form': form,
#         'post': post,
#     })


class PostCreateView(CreateView):
    model = Post
    form_class = PostForm
    template_name = 'instagram/post_new.html'

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.author = self.request.user
        messages.success(self.request, '포스팅을 저장했습니다.')
        return super().form_valid(form)

post_new = PostCreateView.as_view()

# # @csrf_exempt
# @login_required
# def post_new(request):
#     if request.method == 'POST':
#         form = PostForm(request.POST, request.FILES)
#         if form.is_valid():
#             post = form.save(commit=False)
#             post.author = request.user
#             post.save()
#             # post = form.save(commit=False)
#             # post.save()
#             messages.success(request,'포스팅 저장 완료')
#             return redirect(post)
#     else:
#         form = PostForm()
#
#     return render(request, 'instagram/post_new.html',{
#         'form' : form,
#     })

# Create your views here.
# @login_required
# def post_list(request):
#     qs = Post.objects.all()
#     q = request.GET.get('q', '')
#     if q:
#         qs = qs.filter(message__icontains=q)
#
#     # messages.info(request,'messages 테스트')
#     return render(request, 'instagram/post_list.html',{
#         'post_list' : qs,
#         'q' : q,
#     })

# post_list = login_required(ListView.as_view(model=Post, paginate_by=10))
#
# @method_decorator(login_required, name='dispatch' )
# class PostListView(ListView):
#     model = Post
#     paginate_by = 10


class PostListView(LoginRequiredMixin, ListView):
    model = Post
    paginate_by = 10
post_list = PostListView.as_view()


# def post_detail(request: HttpRequest, pk: int) -> HttpResponse:
#     # try:
#     #     post = Post.objects.get(pk=pk) #DoesNotExist
#     # except:
#     #     raise Http404
#
#     post = get_object_or_404(Post,pk=pk)
#     return render(request, 'instagram/post_detail.html',{
#         'post' : post,
#     })

# post_detail = DetailView.as_view(
#     model=Post,
#     # is_public 은 boolean 값
#     queryset=Post.objects.filter(is_public=True)
# )

class PostDetailView(DetailView):
    model = Post

    # 로그인 시 is_public false, true
    # 미로그인은 is_public true
    def get_queryset(self):
        # 재정의 시 super 호출
        # 부모 view가 만든 query set 먼저 호출
        qs = super().get_queryset()
        # 로그인 되어 있으면 is_public True 인 것
        if not self.request.user.is_authenticated:
            qs = qs.filter(is_public=True)
        return qs


post_detail = PostDetailView.as_view()

# def archives_year(request, year):
#     return HttpResponse(f"{year}년 archives")

post_archive = ArchiveIndexView.as_view(model=Post, date_field = 'create_at', paginate_by=10)

post_archive_year = YearArchiveView.as_view(model=Post, date_field='create_at', make_object_list=True  )

templates/instagram/layout.html
{% load static %}
{% load bootstrap4 %}
<!doctype html>
<html lang="ko">
<head>
    <meta charset="utf-8" />
    <title>{% block title %} {% endblock title %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootswatch/4.5.2/lux/bootstrap.min.css" integrity="sha384-9+PGKSqjRdkeAU7Eu4nkJU8RFaH8ace8HGXnkiKMP9I9Te0GJ4/km3L1Z8tXigpG" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
{#    <script src="{% static 'jquery.csrf.js' %}" />#}
</head>
<body>
<nav class="site-header sticky-top py-1">
      <div class="container d-flex flex-column flex-md-row justify-content-between">
        <a class="py-2" href="#">
          <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="d-block mx-auto"><circle cx="12" cy="12" r="10"></circle><line x1="14.31" y1="8" x2="20.05" y2="17.94"></line><line x1="9.69" y1="8" x2="21.17" y2="8"></line><line x1="7.38" y1="12" x2="13.12" y2="2.06"></line><line x1="9.69" y1="16" x2="3.95" y2="6.06"></line><line x1="14.31" y1="16" x2="2.83" y2="16"></line><line x1="16.62" y1="12" x2="10.88" y2="21.94"></line></svg>
        </a>
        <a class="py-2 d-none d-md-inline-block" href="#">Tour</a>
        <a class="py-2 d-none d-md-inline-block" href="#">Product</a>
        <a class="py-2 d-none d-md-inline-block" href="#">Features</a>
        <a class="py-2 d-none d-md-inline-block" href="#">Enterprise</a>
        <a class="py-2 d-none d-md-inline-block" href="#">Support</a>
        <a class="py-2 d-none d-md-inline-block" href="#">Pricing</a>
        <a class="py-2 d-none d-md-inline-block" href="#">Cart</a>
      </div>
    </nav>
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
            {% bootstrap_messages %}
{#            #}
{#            {% if messages %}#}
{#                <div class="messages">#}
{#                {% for message in messages %}#}
{#                        <div class="alert alert-{{ message.tags }}">#}
{#                            {{ message.message }}#}
{#                        </div>#}
{#                {% endfor %}#}
{#                </div>#}
{#            {% endif %}#}


                {% block content %}
                {% endblock content %}
            </div>
        </div>
    </div>

</body>
</html>

templates/instagram/post_archive.html
<h2>latest</h2>

{{ latest }}

<h2>date_list</h2>

{% for date in date_list %}
    {{ date|date:"Y" }}
{% endfor %}

templates/instagram/post_archive_year.html
<h2>year</h2>
{{ year }}
<h2>Previous_year</h2>
{{ previous_year }}
<h2>next year</h2>
{{ next_year }}
<h2>date_list</h2>
{{ date_list }}
<h2>object_list</h2>
{{ object_list }}

templates/instagram/post_confirm_delete.html
{% extends "instagram/layout.html" %}
{% block content %}
    <form action="" method="POST">
        {% csrf_token %}
    <div calss="alert alert-danger">
        정말 삭제하시겠습니까?
    </div>
    <a href="{{  post.get_absolute_url  }}">내용 보기</a>
    <input type="submit" value="삭제" class="btn btn-danger" />
    </form>
{% endblock %}

templates/instagram/post_detail.html
{% extends "instagram/layout.html" %}
{% load bootstrap4 %}

{% block title %}
    Post Detail pk#{{ post.pk }}
{% endblock title %}
{% block content %}
    <h2>Author : {{ post.author }}</h2>

    {% if post.photo %}
        <img src="{{ post.photo.url }}" style="width:100px"/>
    {% else %}
        <h3>No Photo</h3>
    {% endif %}

    {{ post.message }}
    <br/>
    <a href="{% url 'instagram:post_list' %}" class="btn btn-primary">목록</a>
    <a href="{% url 'instagram:post_edit' post.pk %}" class="btn btn-info">수정</a>
    <a href="{% url 'instagram:post_delete' post.pk %}" class="btn btn-danger">삭제</a>

{% endblock %}

templates/instagram/post_list.html
{% extends "instagram/layout.html" %}
{% load bootstrap4 %}

{% block title %}
    Instagram / Post list
{% endblock title %}

{% block content %}
     <form action="" method="get">
        <input type="text" name="q" value="{{ q }}" />
        <input type="submit" value="검색"/>
    </form>

    <a href="{% url 'instagram:post_new' %}" class="btn btn-danger btn-block mt-3 mb-3">새 포스팅</a>

    <table class="table table-bordered table-hover">
        <tbody>
            {% for post in post_list %}
                <tr>
                    <td> {{ post.pk }}</td>
                    <td>
                        {% if post.photo %}
                            <img src="{{ post.photo.url }}" style="width:100px;"/>
                        {% else %}
                            No photo
                        {% endif %}
                    </td>
                    <td>
{#                        <a href="/instagram/{{ post.pk }}/" />#}
{#                        <a href="{% url 'instagram:post_detail' post.pk %}"/>#}
                        <a href="{{ post.get_absolute_url }}"/>
                            {{ post.message }}
                        </a>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

{#    {{ is_paginated }}#}
{#    {{ page_obj }}#}
    {% if is_paginated %}
        {% bootstrap_pagination page_obj size="small" justify_content="center" %}
    {% endif %}
{% endblock content %}

templates/instagram/post_new.html
{% extends "instagram/layout.html" %}
{% load bootstrap4 %}
{% block content %}
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <button class="btn btn-primary">
            저장
            </button>
        {% endbuttons %}
{#        <table>#}
{#            {{ form }}#}
{#        </table>#}
{#        <input type="submit" value="저장" />#}
    </form>
    <br/>
    {% if post %}
        <a href="{{ post.get_absolute_url }}" class="btn btn-info">내용으로</a>
    {% endif %}
{#    {% if form.instance %}#}
{#        <a href="{{ form.instance.get_absolute_url }}">내용으로</a>#}
{#        <a href="{{ form.instance.get_absolute_url }}" class="btn btn-info">내용으로</a>#}
{##}
{#    {% endif %}#}
    <a href="{% url 'instagram:post_list'%}" class="btn btn-primary">목록</a>
{% endblock %}